### ISSUE TITLE
🔥 wake up xiaoyuan bot 🤖

### ISSUE THREAD

**Issue by wj-Mcat** [kaiyuanshe/xiaoyuan#6]
## 背景

小源机器人已经沉默已久，它有一个远大的抱负，希望能够向众人宣传推广开源领域相关的知识，奈何工程师们身心乏术，并没有太多时间来专注于训练提升她的智能性，不过在此希望与大家共同讨论相关话题，推进小源机器人的快速迭代。

## 技术实现

小源机器人有很多功能蓝图，可是需要不断迭代，目前对它的前期定位：能够回复知识库中开源知识、能够快速完成任务型对话能力建设。

### 开源知识库回复

这部分就直接基于语义检索技术来做就行了，鉴于目前主要是中文场景，所以会考虑使用paddle rocketqa 框架来完成。

* [semantic search](https://www.sbert.net/examples/applications/semantic-search/README.html)
* [中文智能问答系统](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering)

### 任务型对话

任务型对话的相关技术比较成熟，可直接使用 rasa 来完成指定任务，也可用一些nlu + state-machine 来构建，相关技术解决方案比较多。

## 讨论

起初小源机器人是不做与具体任务相关的事情，专注于服务于想了解开源知识的人，同时也能够回复一些常识性的问题，可是认为是 ToC 的项目。

可是通过群内沟通，发现目前对小源比较大的需求就是：做一些任务辅助性的功能。比如：翻译组招新引导、工作流程跟踪、翻译术语表维护等等，可以认为是 ToB 的项目。

所以此处的定位还比较模糊。

**Comment by wj-Mcat** [comment]
## 基于ChatGPT 开发小源机器人

目前 chatgpt 已经能够把我们完成大量的工作，包括：任务型对话、自定义结构化文档回复、以及最基础的开放性知识回复，这些能力能帮助我们开发下一代智能聊天机器人，目前也有很多开源项目在做这一方面的尝试了，比如：

* LLM 开发利器： https://github.com/hwchase17/langchain
* 自定义知识库向量工具：https://gpt-index.readthedocs.io/en/latest/index.html
* 自定义文件类型加载工具：https://llamahub.ai/
* 状态机管理：https://github.com/pytransitions/transitions

理论上基于以上工具可开发出满足小源蓝图 1.0 的所有功能，可是这个周期会比较长。

**Comment by TechQuery** [comment]
> 目前 chatgpt 已经能够把我们完成大量的工作，包括：任务型对话、自定义结构化文档回复、以及最基础的开放性知识回复，这些能力能帮助我们开发下一代智能聊天机器人

@wj-Mcat XiaoYuan has woke up: 
- 会议纪要：https://kaiyuanshe.feishu.cn/docx/HrpldpLo1o9ymYxQJGPca6gEnxh#HnHCdEj13ofmBBxTC0DcXPDRncv
- 整编数据：https://aitable.ai/share/shrZ55UyQDq9ktTEHw924/dstGFgzMKN1Uls0WcC/viwvdSncvtWB6?spaceId=spcoDN4LQGC9M
- 挂件开发：kaiyuanshe/kaiyuanshe.github.io#189
- 测试版本：https://aitable.ai/share/shrLPzmeV2iapzGSowywU
- API 文档：https://developers.aitable.ai/api/create-chat-completions

**Comment by TechQuery** [comment]
> 基于ChatGPT 开发小源机器人

@wj-Mcat 我又做了基于 Coze 的试验版：
1. 墙外 GPT-4 模型：https://t.me/xiaoyuan_v2_bot
2. 墙内云雀大模型：https://doubao.com/bot/uBTTVHEY
